# Stub file for common.ipynb
# Auto-generated from notebook code cells

from typing import Any, Callable, Iterable, List, Optional, Tuple, Union
from torch import Tensor

def _equal(a, b): ...
def _almost(a, b, atol=0.01): ...
def check_eq(a: Any, b: Any, atol=None): ...
def assert_eq(a: Any, b: Any, atol=None): ...
def assert_ne(a: Any, b: Any): ...
def assert_lt(a: Any, b: Any): ...
def assert_le(a: Any, b: Any): ...
def assert_gt(a: Any, b: Any): ...
def assert_ge(a: Any, b: Any): ...
def T(x): ...
def count(vector): ...