# Stub file for entropy.ipynb
# Auto-generated from notebook code cells

from typing import Any, Callable, Iterable, List, Optional, Tuple, Union

def _entropy_d(dist, norm): ...
def _entropy_s(samples): ...
def entropy(vector, norm=False, count=False): ...