# Stub file for log_reg_2C_sgd_gradient.ipynb
# Auto-generated from notebook code cells

from typing import Any, Callable, Iterable, List, Optional, Tuple, Union
from torch import Tensor

def Patient2C(sick: float) -> Patient: ...
def _linear(X: Tensor, W: Tensor, b: Tensor) -> Tensor: ...
def _model(X: Tensor, W: Tensor, b: Tensor) -> Tensor: ...
def _sigmoid(X: Tensor) -> Tensor: ...
def _binaryCrossEntropy(P: Tensor, Y: Tensor) -> Tensor: ...
def _loss(P: Tensor, Y: Tensor) -> Tensor: ...
def logistic_regression_2c_sgd_gradient(X: Tensor, Y: Tensor, epochs=2000, lr=0.1) -> tuple[float, callable]: ...