# Stub file for log_reg_ND_sgd_gradient.ipynb
# Auto-generated from notebook code cells

from typing import Any, Callable, Iterable, List, Optional, Tuple, Union

def _Model(X, w, b): ...
def _Sigmoid(m): ...
def _Loss(S, y): ...
def logistic_regression_sgd_gradient(X, y, epochs=2000, lr=0.01): ...