# Stub file for log_reg_ND_sgd_gradient.ipynb
# Auto-generated from notebook code cells

from typing import Any, Callable, Iterable, List, Optional, Tuple, Union

def _Linear(X: Tensor, w: Tensor, b: Tensor) -> Tensor: ...
def _Model(X: Tensor, w: Tensor, b: Tensor) -> Tensor: ...
def _Sigmoid(m: Tensor) -> Tensor: ...
def _BinaryCrossEntropy(S: Tensor, y: Tensor) -> Tensor: ...
def _Loss(S: Tensor, y: Tensor) -> Tensor: ...
def logistic_regression_sgd_gradient(X: Tensor, y: Tensor, epochs=2000, lr=0.1) -> tuple[float, callable]: ...