# Stub file for probability.ipynb
# Auto-generated from notebook code cells

from typing import Any, Callable, Iterable, List, Optional, Tuple, Union

def prob(iterable, cond): ...
def prob_or(iterable, cond1, cond2, *conds): ...
def prob_and(iterable, cond1, cond2, *conds): ...
def prob_cond(iterable, cond_x, cond_y1, *cond_ys): ...