# Stub file for probability.ipynb
# Auto-generated from notebook code cells

from typing import Any, Callable, Iterable, List, Optional, Tuple, Union
import torch as tr

def prob(iterable, cond: callable) -> float: ...
def prob_or(iterable, cond1: callable, cond2: callable, *conds: callable) -> float: ...
def prob_and(iterable, cond1: callable, cond2: callable, *conds: callable) -> float: ...
def prob_cond(iterable, cond_x: callable, cond_y1: callable, *cond_ys: callable) -> float: ...