# Stub file for sigmoid.ipynb
# Auto-generated from notebook code cells

from typing import Any, Callable, Iterable, List, Optional, Tuple, Union

def _sigmoid_f_neg(x: float) -> float: ...
def _sigmoid_f_pos(x: float) -> float: ...
def _sigmoid_f(x: float) -> float: ...
def sigmoid(x: torch.Tensor) -> torch.Tensor: ...